<div class="app-content">
    <div id="tools" class="tools">
        <div class="tools-content">
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
            <div class="tools-add-div"><a href="#">add div</a></div>
        </div>
        <div id="tools-opener" class="tools-opener">
            <div class="arrow-right"></div>
        </div>
    </div>
    
    <div id="options" class="options">
        <div class="options-content">
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
        </div>
        <div id="options-opener" class="options-opener">
            <div class="arrow-left"></div>
        </div>
    </div>
    <div id="navegador" class="navegador">
        <div id="content-xml">
            <?php $this->content() ?>
        </div>
    </div>
</div>