<script>
    var Layaout = "<?php print $this->getFileMap() ?>";
</script>

<div class="app-content">
    <div id="tools" class="tools">
        <div class="tools-content">
            <div class="tools-add-button divdragadd" data-type="Button">button</div>
            <div class="tools-add-textbox divdragadd" data-type="TextBox">textbox</div>
            <div class="tools-add-div divdragadd" data-type="Text">text</div>
        </div>
        <div id="tools-opener" class="tools-opener">
            <div class="arrow-right"></div>
        </div>
    </div>
    <div id="options" class="options">
        <div class="options-content">
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
            <div class="logout"><a href="#">logout</a></div>
        </div>
        <div id="options-opener" class="options-opener">
            <div class="arrow-left"></div>
        </div>
    </div>
    <div id="navegador" class="navegador">
        <div id="content-xml" class="divdrop">
            <?php print $this->content() ?>
            <div class="divdragmove" data-id="@+id/Text1">test</div>
        </div>
    </div>
    <div id="message-box"></div>
</div>